name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ "master" ]
    
env:
  MODEL_NAME: taxi_fare_regressor
  MODEL_VERSION: 1
  MLFLOW_TRACKING_URI: databricks
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.5

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install mlflow
      
      - name: download model artifacts from workspace
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            from mlflow.tracking import MlflowClient
            import mlflow
            import shutil

            client = MlflowClient()
            model_version = client.get_model_version(
              name = os.environ["MODEL_NAME"],
              version = os.environ["MODEL_VERSION"]
            )
            run_id = model_version.run_id
            print(f"run id: {run_id}")

            # Download the artifact to local storage.
            local_dir = "ml_artifacts"
            remote_dir = "train/model"
            os.mkdir(local_dir)
            print(f"local_dir: {local_dir}")
            print(f"local dir full path: {os.path.abspath(local_dir)}")
            local_path = client.download_artifacts(run_id, remote_dir, local_dir)

            full_path = f"{local_dir}/{remote_dir}"
            print(f"Artifacts downloaded in {full_path}: {os.listdir(full_path)}")

            for file in os.listdir(full_path):
              shutil.copy2(os.path.join(full_path, file), "./service/ml_artifacts")            
            print(f"artifacts moved to service folder {os.listdir('./service/ml_artifacts')}")

